package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPointGoods;
import org.linlinjava.litemall.db.domain.LitemallPointGoodsExample;

public interface LitemallPointGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    long countByExample(LitemallPointGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPointGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    int insert(LitemallPointGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPointGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    LitemallPointGoods selectOneByExample(LitemallPointGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    LitemallPointGoods selectOneByExampleSelective(@Param("example") LitemallPointGoodsExample example, @Param("selective") LitemallPointGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    List<LitemallPointGoods> selectByExampleSelective(@Param("example") LitemallPointGoodsExample example, @Param("selective") LitemallPointGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    List<LitemallPointGoods> selectByExample(LitemallPointGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    LitemallPointGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPointGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    LitemallPointGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    LitemallPointGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPointGoods record, @Param("example") LitemallPointGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPointGoods record, @Param("example") LitemallPointGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPointGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPointGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallPointGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_point_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}